### PR TITLE
Vapor3

### PR DESCRIPTION
**Pull request by bre7**

### CODE REVIEW

**Comment by 0xTim** [comment]
Awesome thanks for this! Couple of things I've noticed on the first skim - the dependencies are being injected in, which doesn't play nice with Vapor 3's lack of thread safety. Can you move them to be created from the request instead? Like `let renderer = try req.make(ViewRenderer.self)`?

**Comment by bre7** [comment]
Sure, thanks for the input & quick response 👍 

So instead of dep injection, create them from the current request inside `respond(to:chainingTo:)` ?

```swift
public func respond(to request: Request, chainingTo next: Responder) throws -> EventLoopFuture<Response> {
        let log: Logger = try request.make(ConsoleLogger.self)
        let renderer: TemplateRenderer = try request.make(LeafRenderer.self)

```

**Comment by bre7** [comment]
Tim, one more thing: Is it just me or will HTTP errors not be converted to AbortErrors ? While testing, the `catch` was never be called.

**Comment by 0xTim** [comment]
Yeah exactly for getting the different dependencies. I'll have a think about whether it would be better to do `req.make(LeafRenderer.self)` as that's going to make testing difficult or `req.make(ViewRenderer.self)` as that requires people to set up their config correctly (though that can be mitigated with documentation).

For how it should all work. I would probably throw most of it away and start from scratch since things has changed so much in Vapor. It might be easier to base it off the Vapor 3 Error Middleware rather than trying to port it over (https://github.com/vapor/vapor/blob/master/Sources/Vapor/Middleware/ErrorMiddleware.swift)

**Comment by bre7** [comment]
Great, I'll have a look at ErrorMiddleware (I've been using a clone to convert API errors to JSON payloads)

See #4

**Pull request closed without merging**
